consul:    
       command:  agent -server -bootstrap-expect=1 -bind=0.0.0.0 -node=node1 -client 0.0.0.0  -ui  -join 127.0.0.2
       image: consul:latest
       hostname: "registry"
       ports: 
          - "8300:8300"
          - "8400:8400"
          - "8500:8500"
          - "8600:53/udp"
web:
    command: --registry_address=registry:8500 --register_interval=5 --register_ttl=10   web 
    build: ./IhomeWeb
    links: 
       - consul
    ports: 
       - "8990:8990"
getarea:
    command: --registry_address=registry:8500 --register_interval=5 --register_ttl=10   getarea
    build: ./GetArea
    links:
       - consul
getimagecd:
    command: --registry_address=registry:8500 --register_interval=5 --register_ttl=10   getimagecd
    build: ./GetImageCd
    links:
       - consul
getsmscd:
    command: --registry_address=registry:8500 --register_interval=5 --register_ttl=10   getsmscd
    build: ./GetSmscd
    links:
       - consul
postreg:
    command: --registry_address=registry:8500 --register_interval=5 --register_ttl=10   postreg
    build: ./PostReg
    links:
       - consul
getsession:
    command: --registry_address=registry:8500 --register_interval=5 --register_ttl=10   getsession
    build: ./GetSession
    links:
       - consul
postlogin:
    command: --registry_address=registry:8500 --register_interval=5 --register_ttl=10   postlogin
    build: ./PostLogin
    links:
       - consul
deletesession:
    command: --registry_address=registry:8500 --register_interval=5 --register_ttl=10   deletesession
    build: ./DeleteSession
    links:
       - consul
getuserinfo:
    command: --registry_address=registry:8500 --register_interval=5 --register_ttl=10   getuserinfo
    build: ./GetUserInfo
    links:
       - consul
postavatar:
    command: --registry_address=registry:8500 --register_interval=5 --register_ttl=10   postavatar
    build: ./PostAvatar
    links:
       - consul
posthousesimage:
    command: --registry_address=registry:8500 --register_interval=5 --register_ttl=10   posthousesimage
    build: ./PostHousesImage
    links:
       - consul
getuserhouse:
    command: --registry_address=registry:8500 --register_interval=5 --register_ttl=10   getuserhouse
    build: ./GetUserHouses
    links:
       - consul
posthouses:
    command: --registry_address=registry:8500 --register_interval=5 --register_ttl=10   posthouses
    build: ./PostHouses
    links:
       - consul
postauthuser:
    command: --registry_address=registry:8500 --register_interval=5 --register_ttl=10   postauthuser
    build: ./PostAuthUser
    links:
       - consul
getindex:
    command: --registry_address=registry:8500 --register_interval=5 --register_ttl=10   getindex
    build: ./GetIndex
    links:
       - consul